export const AppActions = {
  ADD_STATE: "ADD_STATE",
  DELETE_STATE: "DELETE_STATE",
  SET_START_STATE: "SET_START_STATE",
  ADD_FINAL_STATE: "ADD_FINAL_STATE",
  DELETE_FINAL_STATE: "DELETE_FINAL_STATE",
  ADD_TRANSITION: "ADD_TRANSITION",
  DELETE_TRANSITION: "DELETE_TRANSITION",
  RESET: "RESET",
};
